#the_robot:
# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
  
# Position Controllers ---------------------------------------
the_robot__palm_left_finger_position_controller:
  type: effort_controllers/JointPositionController
  joint: the_robot__palm_left_finger
  pid: {p: 100.0, i: 0.01, d: 10.0}
the_robot__left_finger_tip_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: the_robot__left_finger_tip_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
the_robot__palm_right_finger_position_controller:
  type: effort_controllers/JointPositionController
  joint: the_robot__palm_right_finger
  pid: {p: 100.0, i: 0.01, d: 10.0}
the_robot__right_finger_tip_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: the_robot__right_finger_tip_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
the_robot__palm_riser_position_controller:
  type: effort_controllers/JointPositionController
  joint: the_robot__palm_riser
  pid: {p: 100.0, i: 0.01, d: 10.0}

#the_robot__left_wheel_hinge_position_controller:
#  type: velocity_controllers/JointVelocityController #effort_controllers/JointPositionController
#  joint: the_robot__left_wheel_hinge
#  pid: {p: 10000.0, i: 1.0, d: 1000.0}






#gazebo_ros_control:
# pid_gains:
#  the_robot__left_wheel_hinge:
#   p: 100.0
#   i: 0.01 
#   d: 10.0

#gazebo_ros_control:
# pid_gains:
#  the_robot__right_wheel_hinge:
#   p: 100.0
#   i: 0.01 
#   d: 10.0
